from __future__ import annotations

APP_ID = "pchat"
APP_NAME = "P-Chat"
APP_VERSION = "1.0.0"

DATA_DIR_NAME = ".pchat"
CONFIG_FILE = "config.json"
DATABASE_FILE = "data.db"

DEFAULT_ROOM_NAME = "main"

DISCOVERY_MAGIC = "PCHAT_DISCOVER_V1"
DISCOVERY_PORT = 8977
CHAT_PORT = 9000
HTTP_PORT = 9100
CONTROL_PORT = 9001

CHAT_ACK_TIMEOUT = 3.0
HOST_PING_INTERVAL = 3.0
HOST_TIMEOUT = 9.0
ELECTION_TIMEOUT = 3.0

SYNC_MESSAGE_LIMIT = 50
HISTORY_DEFAULT_LIMIT = 20

CERT_FILE = "cert.pem"
KEY_FILE = "key.pem"
